"""Add individual admin permissions to User model

Revision ID: 522e995c18dd
Revises: 8c1bb63f0c31
Create Date: 2025-06-11 03:54:39.414017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522e995c18dd'
down_revision = '8c1bb63f0c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_access_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_users', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_categories', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_documents', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_confidential', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_audit_logs', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_system', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_stats', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_view_stats')
        batch_op.drop_column('can_manage_system')
        batch_op.drop_column('can_view_audit_logs')
        batch_op.drop_column('can_view_confidential')
        batch_op.drop_column('can_delete_documents')
        batch_op.drop_column('can_manage_categories')
        batch_op.drop_column('can_manage_users')
        batch_op.drop_column('can_access_admin')

    # ### end Alembic commands ###
